name: ecommerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utitlity packages

  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1
  flutter_native_splash: ^2.4.0

  #icons
  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #product specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_core: ^2.30.0
  lottie: ^3.1.0
  connectivity_plus: ^6.0.2
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 300
          style: italic
