// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09mHej53toE5w3Rpo6PHn9pLlYKwXyUY',
    appId: '1:189816040851:web:06f966384bb68889b94c66',
    messagingSenderId: '189816040851',
    projectId: 'hivekart-76dba',
    authDomain: 'hivekart-76dba.firebaseapp.com',
    storageBucket: 'hivekart-76dba.appspot.com',
    measurementId: 'G-DMYY6ST5VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gi12XV4KtSaKNuqZaGyl9pfSIs6sGOM',
    appId: '1:189816040851:android:083706a3525ac6d3b94c66',
    messagingSenderId: '189816040851',
    projectId: 'hivekart-76dba',
    storageBucket: 'hivekart-76dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIFfeN5jXPae_KA1KgJ2fHP3b5iDJP38',
    appId: '1:189816040851:ios:426b457ce9e66bc2b94c66',
    messagingSenderId: '189816040851',
    projectId: 'hivekart-76dba',
    storageBucket: 'hivekart-76dba.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIFfeN5jXPae_KA1KgJ2fHP3b5iDJP38',
    appId: '1:189816040851:ios:426b457ce9e66bc2b94c66',
    messagingSenderId: '189816040851',
    projectId: 'hivekart-76dba',
    storageBucket: 'hivekart-76dba.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD09mHej53toE5w3Rpo6PHn9pLlYKwXyUY',
    appId: '1:189816040851:web:214db01c1177c43cb94c66',
    messagingSenderId: '189816040851',
    projectId: 'hivekart-76dba',
    authDomain: 'hivekart-76dba.firebaseapp.com',
    storageBucket: 'hivekart-76dba.appspot.com',
    measurementId: 'G-13G5YBW8MW',
  );
}
